# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    use_sim_time: true


    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    tip_controller:
      type: position_controllers/GripperActionController


    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - bicept_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint1
      - wrist_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
tip_controller:
  ros__parameters:
    joints:
      []